### ISSUE TITLE
nxtowz unresolved external symbol on vs2015

### ISSUE THREAD

**Issue by KururuLABO** [NoLifeDev/NoLifeStory#40]
Hi, i try to compile lastest source from github. But i have 1 problem and i try to google too long time and can't fix it.

Error LNK2001
> unresolved external symbol "__declspec(dllimport) public: static class std::locale::id std::codecvt<char16_t,char,struct _Mbstatet>::id" (__imp_?id@?$codecvt@_SDU_Mbstatet@@@std@@2V0locale@2@A)

wztonx.cpp
> #ifndef NL_NO_CODECVT
    std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> convert;

can you help me?

**Comment by retep998** [comment]
The latest source uses `std::wstring_convertstd::codecvt_utf8_utf16<wchar_t, wchar_t> convert;`. I tested it and it works fine for me on my end using VS 2015.

**Comment by KururuLABO** [comment]
Ah it's working fine. When i testing i got error Failed to map view of file on version v149 or newer.
So before you updated new version(3 days ago from now). 
It's working fine (prebuild binaries from rz topic) and get Error  - Writing bitmaps(Report this: -3: 0x78 0x9c) on v117+ or newer(i didn't have client below v117 ).

**Comment by retep998** [comment]
Oh, I haven't updated the prebuilt binaries in a while. I should update them.

**Comment by KururuLABO** [comment]
Yes, i already updated from lastest your git, but still don't work on v149 or higher. When try to convert wz to nx. I'll got failed to map view of file.

**Comment by retep998** [comment]
Oh, you need to make sure you're building for 64-bit mode. 32-bit mode is hamstrung by the tiny address space and is thus unable to map those large WZ files into memory. 32-bit is basically unusable for anything except the really old versions of MapleStory like v40b.

**Comment by KururuLABO** [comment]
So i try to build in 64bit mode but zlib don't working (An internal error has occured in the compliter zutil.c:310). 
ps.I take lib from your sdk.
ps2.in 32 bit it's working fine.

**Comment by retep998** [comment]
The sdk was rather outdated and built using an old version of VS. I just updated it so now it should work fine.

**Comment by KururuLABO** [comment]
Ah it's working everything. I will be close this issue topic.
Thank you for support. :+1:
