### ISSUE TITLE
WzToNx Crash when processing Data.wz, Map.wz, Mob.wz, UI.wz

### ISSUE THREAD

**Issue by stephen304** [NoLifeDev/NoLifeStory#44]
stephen@Jupiter ~/git/NoLifeStory/src/wztonx (git)-[master] % ./NoLifeWzToNx -client Data.wz 
    NoLifeWzToNx
    Copyright © 2014 Peter Atashian
    Licensed under GNU Affero General Public License
    Converts WZ files into NX files
    Data.wz -> Data.nx
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Not a valid WZ file
    Parsing input.......[1]    12663 abort (core dumped)  ./NoLifeWzToNx -client Data.wz

Not sure why this is happening, the game works fine, all the other .wz files converted fine. Ideas?

**Comment by retep998** [comment]
`  what():  Not a valid WZ file`
`if (magic != 0x31474B50) throw std::runtime_error("Not a valid WZ file");`
That WZ file doesn't look like a WZ file. Could you perhaps upload it so I could take a look at it? What version of MapleStory is it from?

**Comment by stephen304** [comment]
Well, that's what I assumed too so I validated the files and launched the game and it all seems to be running fine. Here's the Data.wz - all the other ones are much larger so I'll hope whatever the fix is for this one works for the rest: http://filebin.net/0xyo7gpdi2/Data.wz

It's from the latest Maplestory.

**Comment by retep998** [comment]
That Data.wz you have uploaded is not a WZ file at all. In fact its existence is probably an accident and if you delete it MapleStory should continue to work fine. I don't have a Data.wz in my local installation of GMS so I'm not sure how you got it.

**Comment by stephen304** [comment]
Huh that's weird... Well my install is a bit old so maybe they removed it and it just never got deleted. Do you have the other ones, Map.wz, Mob.wz, or UI.wz?

**Comment by retep998** [comment]
I have all the other WZ files. Data.wz was a relic from the beta days when they stored all the data in a single WZ file. They later split everything into multiple files with Base.wz acting as a root of sorts. You should have absolutely no reason to have a Data.wz unless either Nexon accidentally included a file with that name in a patch or your MapleStory installation is nearly a decade old.

Anyway, closing since there's nothing for me to fix.

**Comment by stephen304** [comment]
What's the md5 for your other 3 wz files? Those ones still error out for me and they validate fine in steam.

**Comment by stephen304** [comment]
stephen@Jupiter ~/git/NoLifeStory/src/wztonx (git)-[master] % ./NoLifeWzToNx -client UI.wz
    NoLifeWzToNx
    Copyright © 2014 Peter Atashian
    Licensed under GNU Affero General Public License
    Converts WZ files into NX files
    UI.wz -> UI.nx
    [1]    32403 segmentation fault (core dumped)  ./NoLifeWzToNx -client UI.wz

**Comment by stephen304** [comment]
Or preferably sha512 or sha1 cause 7z has a checksum thing on windows for those

**Comment by retep998** [comment]
Oh, your issue is about several WZ files, not just Data.wz. I have replicated the issue, it is probably just some new property type I don't handle yet.

**Comment by retep998** [comment]
Oh, it's actually a string that's longer than the max length I support. I probably should make it dynamically generate the string key as needed instead of using a precomputed key with a fixed length.

Here's the string itself: https://gist.github.com/retep998/d6a4327106167a8f7e84

**Comment by stephen304** [comment]
Oh nifty good work! I'm looking forward to being able to get this to work on linux

**Comment by retep998** [comment]
For now I recommend using an older version of MapleStory before they added the skeleton animation stuff.

**Comment by mspencer92** [comment]
I am having the same error it seems when using WzToNx on v169 files. Is there an eta for a fix?
Thanks, Michael

**Comment by retep998** [comment]
As it turns out, this was easier to fix than I expected. The key really does have a max length of 0x10000 and after that the rest is just 0.

**Comment by stephen304** [comment]
Awesome great work! I'm able to launch the game now, albeit to a black screen.

**Comment by retep998** [comment]
That's because the flag is actually `--client` and not `-client`.

**Comment by stephen304** [comment]
Ah, maybe if the readme could be updated with `--` and `NoLifeWzToNx` could print a basic usage example with `-h` it would be a lot more clear

**Comment by mspencer92** [comment]
Thank you for the fix. Are there prebuit binarys or do I have to build this version myself?

**Comment by retep998** [comment]
I have updated the prebuilt binaries on dropbox with the latest version of NoLifeWzToNx.

**Comment by mspencer92** [comment]
Thank you, you are the best.
