### ISSUE TITLE
The Index of u16key[i] is out of range 

### ISSUE THREAD

**Issue by xsoameix** [NoLifeDev/NoLifeStory#48]
These lines in [`wztonx.cpp`](https://github.com/NoLifeDev/NoLifeStory/blob/master/src/wztonx/wztonx.cpp#L367)

    for (auto i = 0u; i < std::min(slen, 0x10000u); ++i) {
        wstr_buf[i] = static_cast<char16_t>(ows[i] ^ u16key[i] ^ mask);
        ...

should be

    for (auto i = 0u; i < std::min(slen, 0x10000u / 2u); ++i) {
        wstr_buf[i] = static_cast<char16_t>(ows[i] ^ u16key[i] ^ mask);
        ...

Since `u16key` is `char16_t`, the index `i` would be multiplied by 2 to get the character `u16key[i]`.
If `i` is 0x10000u, the index of `u16key[0x10000u]` will be calculated as `u8key[0x20000u]`, which will be out of range. It may cause segment fault, because the size of `u16key` is only 0x10000u bytes.

**Comment by ghost** [comment]
I would like to add that I can't attack mobs, use skills, enter the Cash Shop, charge NX, do quests, or many other things in NoLifeStory.

**Comment by retep998** [comment]
Yeah, this seems like it was an oversight. Do you have any examples of a WZ file that actually has a wide string over 0x8000 in length? It would definitely help to confirm what the actual behavior should be.

@barryanders Your comment is entirely unrelated to the issue at hand and counterproductive.

**Comment by xsoameix** [comment]
I don't have any examples of wz files that wide string length is larger than 0x8000u. I am writing the code of the same logic now, and need some examples to confirm the actual behavior too, so I read your code to check whether you had already encountered this problem.

Something will happened when wide string is over 0x8000u. Maybe there is a segment fault luckily or wide string over 0x8000u is incorrectly decrypted since `key_bms`, `key_gms`, and `key_kms` are put together and makes problem more complexed. I have not test this.

Throwing a exception and telling the user what error is is the best choice to let this issue more easily be seen and supported in the future. The second choice is just dividing by 2 to make the code more readable or changing the value to 0x8000u.
The last choice is doing nothing and wait for someone to find the issue in the future.

The choice is up to you. This issue in some point of view is solved. I can close this issue if you want :).

**Comment by retep998** [comment]
The reason I wrote that code in the first place is some narrow strings that have a length over 0x10000. In particular giant json blobs for the new skeleton animation system. I'll probably just report an error in the wide string case if it is over 0x8000 so people can report what wz file causes the error so I can test how it should actually be decoded.

**Comment by xsoameix** [comment]
That will be great, thank you for your quick and nice response :).

**Comment by ghost** [comment]
Sorry @retep998, My response was intended to be humorous.
